// Generated by Wrangler on Fri Aug 30 2024 14:49:51 GMT+0200 (GMT+02:00)
// by running `wrangler types`

interface Env {
	rate_limiter: KVNamespace;
	RAG_SYNC_TOKEN: string;
	BLOG_CORPUS_ID: string;
	EMBEDDING_MODEL: string;
	CHAT_MODEL: string;
	BLOG_SITE_URL: string;
	DB: D1Database;
	VECTORIZE_INDEX: VectorizeIndex;
	AI: Ai;
	POST_ASSETS: R2Bucket;
}
