import { createPagesFunctionHandler } from "@remix-run/cloudflare-pages";
import { authorizeEmbedPageRequest } from "./_shared/embed-access.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore - the server build file is generated by `remix vite:build`
// eslint-disable-next-line import/no-unresolved
import * as build from "../build/server";

const handleRemixRequest = createPagesFunctionHandler({ build });

function buildNotFoundResponse() {
	return new Response("Not Found", {
		status: 404,
		headers: {
			"cache-control": "no-store, no-transform",
			"content-type": "text/plain; charset=utf-8",
		},
	});
}

export const onRequest: PagesFunction<Env> = async (context) => {
	const url = new URL(context.request.url);

	if (url.pathname === "/") {
		return buildNotFoundResponse();
	}

	if (url.pathname === "/embed") {
		return authorizeEmbedPageRequest({
			request: context.request,
			env: context.env,
			renderAuthorized: () => handleRemixRequest(context),
		});
	}

	return handleRemixRequest(context);
};
